name: Promote Python Package

on:
  push:
    branches:
      - main

env:
  CLOUDSMITH_NAMESPACE: "interview-prashant-lahare"  # Replace with the actual namespace
  CLOUDSMITH_STAGING_REPO: "staging"
  CLOUDSMITH_PRODUCTION_REPO: "production"
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_NAME: "python-package"
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
  
permissions:
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        run: pip install --upgrade cloudsmith-cli
        shell: bash
        
      - name: List cloudsmith packages
        run: cloudsmith list packages interview-prashant-lahare/staging
        shell: bash
        
      - name: Ensure correct package
        run: PACKAGE_QUERY="filename:${PACKAGE_NAME}-0.1.0.tar.gz"
        shell: bash
        
      - name: list all available packages
        run: cloudsmith list packages interview-prashant-lahare/staging -F json | jq '.data[].slug'
        shell: bash  
      
      - name: list all repos
        run: cloudsmith list repos interview-prashant-lahare
        shell: bash 
        
      - name: API key must have permission
        run: cloudsmith whoami --api-key 72dc5d23b33fae292be21583529f97005a4ad8d4
        shell: bash
        
      - name: Get package identifier and Tag the synchronized package
        run: |
          # List all packages in the repository
          echo "Fetching all packages in staging repository..."
          PACKAGE_DATA=$(cloudsmith list packages interview-prashant-lahare/staging -F json || echo "{}")

          # Debug: Print the response to check package details
          echo "PACKAGE_DATA: $PACKAGE_DATA"

          # Extract identifier
          IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm // empty')

          # Check if identifier is empty
          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" == "empty" ]; then
            echo "No matching package found in staging!"
            exit 1
          fi

          echo "Found package identifier: $IDENTIFIER"
          echo "Tagging package with 'ready-for-production'"
          cloudsmith tag add ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER ready-for-production

          # Promote package using the identifier
          # cloudsmith mv --yes \
          #   interview-prashant-lahare/staging/$IDENTIFIER \
          #   interview-prashant-lahare/production-mVP7
        shell: bash
        
      - name: Get package identifier and promote
        run: |
          echo "Fetching all packages from staging..."
          PACKAGE_DATA=$(cloudsmith list packages interview-prashant-lahare/staging -F json || echo "{}")

          echo "Raw PACKAGE_DATA:"
          echo "$PACKAGE_DATA" | jq '.data[] | {name: .name, tags: .tags}'

          # Extract identifiers of packages that have the "ready-for-production" tag
          IDENTIFIERS=$(echo "$PACKAGE_DATA" | jq -r '.data[] | select(.tags | contains({version: ["ready-for-production"]})) | .identifier_perm')

          if [ -z "$IDENTIFIERS" ]; then
            echo "No packages found with 'ready-for-production' tag"
            exit 1
          fi

          # Promote each package that has the correct tag
          for IDENTIFIER in $IDENTIFIERS; do
            echo "Promoting package: $IDENTIFIER"
            cloudsmith mv --yes \
              interview-prashant-lahare/staging/$IDENTIFIER \
              interview-prashant-lahare/production
          done
        shell: bash

  
      # - name: Promote tagged packages
      #   run: |
      #     echo "Fetching all packages tagged with 'ready-for-production'"

      #     PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} --tag ready-for-production -F json || echo "{}")

      #     IDENTIFIERS=$(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm')

      #     if [ -z "$IDENTIFIERS" ]; then
      #       echo "No packages found with 'ready-for-production' tag"
      #       exit 1
      #     fi

      #     for IDENTIFIER in $IDENTIFIERS; do
      #       echo "Promoting package: $IDENTIFIER"
      #       cloudsmith mv --yes \
      #         ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
      #         ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
      #     done
      #   shell: bash  
      
